#!/usr/bin/env python3
from __future__ import annotations
import argparse
import json
import os
import random
import shutil
import sys
import time
import traceback
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1]))
import clonegrown as cws
from clonegrown.state import WorkspaceState
from campaign_record import run, GIT_BIN, campaign_environment, state_machine_replay, write_json_atomic


def summary_ref(workspace_state, worker_id):
    return WorkspaceState.from_json(workspace_state).summary_ref(worker_id)

ROOT = Path(os.environ.get('CWS_FUZZ_ROOT', '/tmp/cws-final-state-machine-fuzz'))
WORKTREE = os.environ.get('CWS_SUITE_MODE') == 'worktree'
MODE = 'worktree' if WORKTREE else 'clone'


def git(repo, *args, check=True):
    return run([GIT_BIN, *args], repo, check)


def setup(seed: int):
    case_root = ROOT / f'seed-{seed}'
    shutil.rmtree(case_root, ignore_errors=True)
    case_root.mkdir(parents=True)
    origin = case_root / 'origin.git'
    git(case_root, 'init', '--bare', origin)
    canonical = case_root / 'canonical'
    git(case_root, 'clone', origin, canonical)
    git(canonical, 'config', 'user.name', 'Canonical')
    git(canonical, 'config', 'user.email', 'canonical@example.invalid')
    git(canonical, 'config', 'fuzz.sentinel', 'canonical')
    (canonical / 'README.md').write_text('base\n')
    git(canonical, 'add', '.')
    git(canonical, 'commit', '-m', 'init')
    git(canonical, 'branch', '-M', 'main')
    git(canonical, 'push', '-u', 'origin', 'main')
    workspace = case_root / 'workspace'
    cws.init_workspace(canonical, workspace)
    return case_root, canonical, workspace, str(origin)


def metas(workspace: Path):
    out = {}
    for p in (workspace / '.cws/workers').glob('*.json'):
        if not p.stem.isdigit():
            continue
        out[int(p.stem)] = json.loads(p.read_text())
    return out


def commit(repo: Path, label: str, step: int):
    p = repo / 'fuzz' / f'{step}.txt'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(label+'\n')
    git(repo, 'add', str(p.relative_to(repo)))
    git(repo, 'commit', '-m', label)
    return git(repo, 'rev-parse', 'HEAD').stdout.strip()


def clean(repo: Path):
    git(repo, 'reset', '--hard', 'HEAD')
    git(repo, 'clean', '-fd')


def private_refs(repo: Path, branch: str) -> dict[str, str]:
    """Independent model of the ordinary refs generated by this campaign."""
    refs = {}
    for line in git(repo, 'for-each-ref', '--format=%(refname) %(objectname) %(symref)').stdout.splitlines():
        name, value = line.split(' ', 1)
        if name != f'refs/heads/{branch}':
            refs[name] = value
    return refs


def discard_collected(workspace: Path, worker: dict, baseline: dict[str, str], record):
    worker_id = worker['id']
    repo = Path(worker['path'])
    changed = bool(git(repo, 'status', '--porcelain').stdout.strip())
    branch = git(repo, 'rev-parse', '--verify', f"refs/heads/{worker['branch']}", check=False)
    changed = changed or branch.returncode != 0 or branch.stdout.strip() != worker['result_sha']
    refs_before = private_refs(repo, worker['branch']) if not WORKTREE else {}
    private_changed = refs_before != baseline
    cws.release(workspace, worker_id)
    try:
        cws.discard(workspace, worker_id)
    except cws.ClonegrownError:
        assert changed or private_changed, 'discard refused an unchanged collected worker'
        assert repo.is_dir(), 'refusal removed the worker'
        if not WORKTREE:
            assert private_refs(repo, worker['branch']) == refs_before
        assert metas(workspace)[worker_id]['status'] == 'collected', 'refusal changed durable state'
        record('discard_refused_changed' if changed else 'discard_refused_private_refs', worker_id)
        if private_changed and not changed:
            cws.discard(workspace, worker_id, discard_private_refs=True)
            assert not repo.parent.exists()
            record('discard_acknowledged_private_refs', worker_id)
    else:
        assert not changed, 'discard accepted working-tree or task-branch drift'
        assert not private_changed, 'discard silently deleted changed private refs'
        record('discard', worker_id)


def invariant(canonical: Path, workspace: Path, origin_url: str, full=False):
    if full:
        git(canonical, 'fsck', '--full')
    if not WORKTREE:
        assert git(canonical, 'config', 'fuzz.sentinel').stdout.strip() == 'canonical'  # worktrees share config by design
    assert git(canonical, 'remote', 'get-url', 'origin').stdout.strip() == origin_url
    audit = cws.status(workspace)
    assert audit['issues'] == [], f'workspace audit found {audit["issues"]}'
    workspace_state = json.loads((workspace / '.cws/state.json').read_text())
    workers = metas(workspace)
    assert {worker['id'] for worker in audit['workers']} == set(workers), f'audit/record mismatch: audit={[worker["id"] for worker in audit["workers"]]}, records={sorted(workers)}'
    agent_heads = [l.split()[1] for l in git(canonical, 'show-ref', '--heads').stdout.splitlines() if '/agent/' in l]
    if WORKTREE:
        # Task branches live in canonical's shared refs; each must belong to a worker that still has a directory.
        live = {f"refs/heads/{worker['branch']}" for worker in workers.values() if (workspace / str(worker['id'])).exists()}
        leaked = [h for h in agent_heads if h not in live]
        assert not leaked, f'branches outlived their worktree: {leaked}'
    else:
        assert not agent_heads
    for worker_id, worker in workers.items():
        assert worker['id'] == worker_id
        assert worker['workspace_id'] == workspace_state['workspace_id']
        expected = workspace / str(worker_id) / workspace_state['repo_name']
        assert Path(worker['path']) == expected
        status = worker['status']
        repo = expected
        if status == 'ready':
            assert repo.is_dir()
            assert (repo / '.git').is_file() if WORKTREE else (repo / '.git').is_dir()
            gd = Path(git(repo, 'rev-parse', '--git-dir').stdout.strip())
            gd = gd if gd.is_absolute() else (repo / gd).resolve()
            marker = json.loads((gd / 'cws-worker.json').read_text())
            assert marker['worker_id'] == worker_id
            assert marker['workspace_id'] == workspace_state['workspace_id']
            assert marker['worker_token'] == worker['worker_token']
            assert git(repo, 'show-ref', '--verify', f"refs/heads/{worker['branch']}").returncode == 0
        elif status == 'collected':
            ref = worker['result_ref']
            assert git(canonical, 'rev-parse', ref).stdout.strip() == worker['result_sha']
            assert git(canonical, 'rev-parse', summary_ref(workspace_state, worker_id)).stdout.strip() == worker['result_sha']
        elif status in ('discarded', 'abandoned'):
            assert not repo.parent.exists()
    return True


def one(seed: int, steps: int=100, strong_rate: float=.08):
    rng = random.Random(seed)
    case_root, canonical, workspace, origin = setup(seed)
    events = []
    counts = {}
    private_baselines = {}
    def record(op, *detail):
        counts[op] = counts.get(op, 0)+1
        events.append([len(events), op, *detail])
    try:
        for step in range(steps):
            workers = metas(workspace)
            ready = [i for i, worker in workers.items() if worker['status'] == 'ready']
            collected = [i for i, worker in workers.items() if worker['status'] == 'collected']
            op = rng.choices(
                ['spawn', 'commit', 'dirty', 'collect', 'discard', 'abandon', 'retry', 'mismatch', 'advance', 'mutate', 'recover', 'summary_loss', 'post_collect_change'],
                [14, 13, 5, 13, 9, 6, 8, 4, 7, 8, 7, 3, 3]
            )[0]
            if op == 'spawn' or (not ready and not collected and op in ('commit', 'dirty', 'collect', 'discard', 'abandon', 'mutate', 'post_collect_change')):
                req = f'{seed}-{step}-{rng.randrange(1<<40)}'
                task = rng.choice(['normal', 'unicode Ω λ', '../../escape;echo nope', 'x'*100])
                strong = rng.random() < strong_rate
                worker = cws.spawn(workspace, 'main', task, strong=strong and not WORKTREE, request_id=req, mode=MODE)
                record('spawn', worker['id'], strong)
                private_baselines[worker['id']] = private_refs(Path(worker['path']), worker['branch']) if not WORKTREE else {}
            elif op == 'commit' and ready:
                worker_id = rng.choice(ready)
                repo = Path(workers[worker_id]['path'])
                clean(repo)
                sha = commit(repo, f'commit-{seed}-{step}', step)
                record('commit', worker_id, sha)
            elif op == 'dirty' and ready:
                worker_id = rng.choice(ready)
                repo = Path(workers[worker_id]['path'])
                (repo / f'DIRTY-{step}').write_text('dirty')
                record('dirty', worker_id)
            elif op == 'collect' and ready:
                worker_id = rng.choice(ready)
                repo = Path(workers[worker_id]['path'])
                dirty = bool(git(repo, 'status', '--porcelain').stdout.strip())
                try:
                    cws.collect(workspace, worker_id)
                    assert not dirty
                    record('collect', worker_id)
                except cws.ClonegrownError:
                    assert dirty
                    clean(repo)
                    record('collect_refused_dirty', worker_id)
            elif op == 'discard' and collected:
                worker_id = rng.choice(collected)
                discard_collected(workspace, workers[worker_id], private_baselines[worker_id], record)
            elif op == 'abandon' and (ready or collected):
                worker_id = rng.choice(ready+collected)
                worker = workers[worker_id]
                repo = Path(worker['path'])
                # The lease blocks every published-worker deletion until release; collection is one-shot.
                try:
                    cws.discard(workspace, worker_id, abandon=True)
                    raise AssertionError('abandon accepted a protected worker')
                except cws.ClonegrownError:
                    assert repo.is_dir()
                    assert metas(workspace)[worker_id]['status'] == worker['status']
                cws.release(workspace, worker_id)
                if worker['status'] == 'collected':
                    try:
                        cws.discard(workspace, worker_id, abandon=True)
                        raise AssertionError('abandon accepted a collected worker')
                    except cws.ClonegrownError:
                        assert repo.is_dir()
                        assert metas(workspace)[worker_id]['status'] == 'collected'
                        record('abandon_refused_collected', worker_id)
                else:
                    cws.discard(workspace, worker_id, abandon=True)
                    record('abandon', worker_id)
            elif op == 'retry' and workers:
                worker = rng.choice(list(workers.values()))
                try:
                    got = cws.spawn(workspace, worker['base'], worker['task'], strong=bool(worker['strong']), request_id=worker.get('request_id'), mode=MODE)
                    if worker['status'] in ('spawn_failed', 'abandoned'):
                        assert got['id'] != worker['id'] and got['id'] > worker['id']
                        record('retry_reallocated', worker['id'], got['id'])
                        private_baselines[got['id']] = private_refs(Path(got['path']), got['branch']) if not WORKTREE else {}
                    else:
                        assert got['id'] == worker['id']
                        record('retry', worker['id'])
                except cws.ClonegrownError:
                    # Broken/partial states are allowed to require recovery; no silent aliasing is allowed.
                    assert worker['status'] in ('broken', 'collecting', 'discarding')
                    record('retry_refused', worker['id'])
            elif op == 'mismatch' and workers:
                worker = rng.choice([x for x in workers.values() if x.get('request_id')] or list(workers.values()))
                if worker.get('request_id'):
                    try:
                        cws.spawn(workspace, worker['base'], worker['task']+'-different', strong=bool(worker['strong']), request_id=worker['request_id'], mode=MODE)
                        raise AssertionError('mismatched request accepted')
                    except cws.ClonegrownError:
                        record('mismatch_refused', worker['id'])
            elif op == 'advance':
                p = canonical / f'canon-{step}.txt'
                p.write_text(str(step))
                git(canonical, 'add', p.name)
                git(canonical, 'commit', '-m', f'canon {step}')
                record('advance')
            elif op == 'mutate' and ready:
                worker_id = rng.choice(ready)
                repo = Path(workers[worker_id]['path'])
                choice = rng.choice(['stash', 'reset'] if WORKTREE else ['config', 'remote', 'stash', 'reset'])  # config/remote probes test clone isolation; in a worktree they would edit canonical
                if choice == 'config':
                    git(repo, 'config', 'fuzz.sentinel', 'worker')
                elif choice == 'remote' and 'origin' in git(repo, 'remote').stdout.split():
                    git(repo, 'remote', 'remove', 'origin')
                elif choice == 'stash':
                    (repo / 'scratch').write_text('x')
                    git(repo, 'add', 'scratch')
                    git(repo, 'stash', 'push', '-m', 'w')
                    git(repo, 'stash', 'clear')
                else:
                    clean(repo)
                record('mutate', worker_id, choice)
            elif op == 'recover':
                cws.recover(workspace)
                record('recover')
            elif op == 'summary_loss' and collected:
                worker_id = rng.choice(collected)
                workspace_state = json.loads((workspace / '.cws/state.json').read_text())
                sref = summary_ref(workspace_state, worker_id)
                git(canonical, 'update-ref', '-d', sref)
                cws.recover(workspace)
                assert git(canonical, 'rev-parse', sref).stdout.strip() == workers[worker_id]['result_sha']
                record('summary_repair', worker_id)
            elif op == 'post_collect_change' and collected:
                worker_id = rng.choice(collected)
                repo = Path(workers[worker_id]['path'])
                if repo.exists():
                    clean(repo)
                    commit(repo, f'post-collected-{seed}-{step}', step)
                    cws.release(workspace, worker_id)
                    try:
                        cws.discard(workspace, worker_id)
                        raise AssertionError('discard accepted post-collection commit')
                    except cws.ClonegrownError:
                        record('post_collect_guard', worker_id)
            else:
                cws.recover(workspace)
                record('recover_fallback')
            if step%10 == 0:
                invariant(canonical, workspace, origin, full=True)
        invariant(canonical, workspace, origin, full=True)
        result = {
            'seed': seed,
            'steps': steps,
            'ok': True,
            'events': len(events),
            'workers': len(metas(workspace)),
            'counts': counts,
        }
        shutil.rmtree(case_root, ignore_errors=True)
        return result
    except Exception as e:
        return {
            'seed': seed,
            'steps': steps,
            'ok': False,
            'error': f'{type(e).__name__}: {e}',
            'step': locals().get('step'),
            'op': locals().get('op'),
            'traceback': traceback.format_exc(),
            'events': events,
            'root': str(case_root),
            'counts': counts,
        }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--start', type=int, default=0)
    parser.add_argument('--seeds', type=int, default=10)
    parser.add_argument('--steps', type=int, default=100)
    parser.add_argument('--output', required=True)
    arguments = parser.parse_args()
    if arguments.seeds < 1:
        parser.error('--seeds must be positive')
    if arguments.steps < 1:
        parser.error('--steps must be positive')
    ROOT.mkdir(parents=True, exist_ok=True)
    t = time.perf_counter()
    environment = campaign_environment()
    rows = [{
        'seed': seed,
        'steps': arguments.steps,
        'ok': None,
        'status': 'pending',
        'replay_command': state_machine_replay(MODE, seed, arguments.steps),
    } for seed in range(arguments.start, arguments.start+arguments.seeds)]
    def payload():
        return {
            'schema_version': 1,
            'campaign': 'state-machine',
            'worker': MODE,
            'start': arguments.start,
            'requested_seeds': arguments.seeds,
            'steps_per_seed': arguments.steps,
            'environment': environment,
            'executed': sum(x['ok'] is not None for x in rows),
            'pending': sum(x['ok'] is None for x in rows),
            'passed': sum(x['ok'] is True for x in rows),
            'failed': sum(x['ok'] is False for x in rows),
            'seconds': time.perf_counter()-t,
            'results': rows,
        }
    write_json_atomic(arguments.output, payload())
    for index, seed in enumerate(range(arguments.start, arguments.start+arguments.seeds)):
        r = one(seed, arguments.steps)
        r['status'] = 'passed' if r['ok'] else 'failed'
        r['replay_command'] = state_machine_replay(MODE, seed, arguments.steps)
        rows[index] = r
        write_json_atomic(arguments.output, payload())
        print(('PASS' if r['ok'] else 'FAIL'), seed, json.dumps(r, sort_keys=True), flush=True)
        if not r['ok']:
            break
    out = payload()
    return 1 if out['failed'] else 0
if __name__ == '__main__':
    sys.exit(main())
